package io.asbun.backend.model.enums;

public enum AuditEventType {
    ACCOUNT_DELETION_REQUESTED,
    ACCOUNT_DELETION_COMPLETED,
    ACCOUNT_DELETION_FAILED,
    ACCOUNT_REACTIVATED,
    DATA_EXPORT_REQUESTED,
    DATA_EXPORT_COMPLETED,
    DATA_EXPORT_FAILED,
    CONSENT_GRANTED,
    CONSENT_REVOKED,
    SCHEDULED_DELETION_RUN
}
